export const  SET_TOSS_CALLER = 'SET_TOSS_CALLER';
export const  SET_TOSS_CALL = 'SET_TOSS_CALL';
export const SET_TOSS_SELECTED ='SET_TOSS_SELECTED';
export const SET_TOSS_WINNER = 'SET_TOSS_WINNER';
export const SET_TOSS_COMPLETED = 'SET_TOSS_COMPLETED'; 